export const USERS_LISTS_IS_LOADING = 'USERS_LISTS_IS_LOADING';
export const USERS_LISTS_HAS_LOADED = 'USERS_LISTS_HAS_LOADED';
export const ERROR_LOAD_LIST = 'ERROR_LOAD_LIST';
export const FETCH_FOR_LIST = 'FETCH_FOR_LIST';
export const SAVE_USER_RECIPIENT = 'SAVE_USER_RECIPIENT';
export const SAVE_USER_RECIPIENT_TO_STATE= 'SAVE_USER_RECIPIENT_TO_STATE';
export const DELETE_USER_RECIPIENT_FROM_STATE= 'DELETE_USER_RECIPIENT_FROM_STATE';